#!/usr/bin/env bash
alias c="clear"
alias b='pushd'
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias brc="vim ~/.bashrc"

alias l="ls -lah"

if is_macos ; then
  alias pbc='pbcopy'
  alias pbp='pbpaste'
else
  alias pbc='xclip -selection clipboard'
  alias pbp='xclip -o'
fi
alias szsh='source ~/.zshrc'

if is_ubuntu ; then
  if command_exists 'gdb' ; then
    alias cdebug='gdb --batch --ex bt --ex run --ex q --args '
  fi
fi
