#!/usr/bin/env bash

# shellcheck disable=1090
[ -f "$HOME/dotfiles/bin/dotfiles.env" ] && . "$HOME/dotfiles/bin/dotfiles.env"
# shellcheck disable=1090
[ -f "$DOTFILES_BIN/nvm/nvm.sh" ] && . "$DOTFILES_BIN/nvm/nvm.sh"
export PATH="/usr/local/bin:$DOTFILES_BIN:$PATH"
