#!/usr/bin/env bash

if [ -f "$HOME/dotfiles/bin/dotfiles.env" ] ; then
  # shellcheck disable=1090
  . "$HOME/dotfiles/bin/dotfiles.env"
fi
if [ -f "$DFILES/bin/nvm/nvm.sh" ] ; then
  # shellcheck disable=1090
  . "$DFILES/bin/nvm/nvm.sh"
fi
if [ -f "$SDKMAN_DIR/bin/sdkman-init.sh" ] ; then
  # shellcheck disable=1090
  . "$SDKMAN_DIR/bin/sdkman-init.sh"
fi
export PATH="/usr/local/bin:$DFILES/bin:$PATH"
