#!/usr/bin/env bash

#wget -qO- "https://raw.githubusercontent.com/nvm-sh/nvm/$DOTFILES_NVM_VERSION/install.sh" | bash
curr=$(pwd)
clone_from_github 'nvm-sh/nvm' "${DOTFILES_NVM_VERSION:-0.35.2}"
"$DOTFILES_NVM_DIR"/install.sh
cd "$curr" || exit 1

sudo chmod +x "$DOTFILES_NVM_DIR/nvm.sh"

# shellcheck disable=1090
. "$DOTFILES_NVM_DIR/nvm.sh" 

nvm install "${DOTFILES_NODE_VERSION:-12.16.1}"

