#!/usr/bin/env bash

#wget -qO- "https://raw.githubusercontent.com/nvm-sh/nvm/$DOTFILES_NVM_VERSION/install.sh" | bash
curr=$(pwd)
clone_from_github 'nvm-sh/nvm' 'v0.35.2'
"$DOTFILES_NVM_DIR"/install.sh
cd "$curr" || exit 1

nvm install "12.16.1"
