#!/usr/bin/env bash

function update_github_repo () {
  git pull origin master
}

function update_package_managers () {
  if is_ubuntu ; then sudo apt-get -y update
  elif is_macos ; then brew update 
  elif is_rpi ; then sudo apt-get -y update
  else
    echo 'No package manager to update, continuing'
  fi
}

function check_is_root () {
  if ! (( "${DOTFILES_SHOULD_STOP_CURRENT:-0}" )) ; then
    if ! [ "$(id -u)" -eq 0 ] ; then
      export DOTFILES_SUDO_REQUIRED=1
      export DOTFILES_SHOULD_STOP_CURRENT=1
    fi
  fi
}

function install_with_npm () {
  cmd='npm install -g --save-dev'
  while read -r -d ' ' package
  do
    cmd="$cmd $package"
  done < <(echo "$1 ")
  echo "NPM Command: $cmd"
  eval "$cmd"
}

function install_with_pip () {
  cmd='pip install'
  while read -r -d ' ' package
  do
    cmd="$cmd $package"
  done < <(echo "$1 ")
  eval "$cmd"
}

function install_with_cargo () {
  cmd='cargo install --force'
  while read -r -d ' ' package
  do
    cmd="$cmd $package"
  done < <(echo "$1 ")

  eval "$cmd"
}

function install_with_go_get () {
  go get "$1"
}

function install_with_curl () {
  curl -sSL "$1" | bash
}

function install_with_pkg_manager () {
  set +e
  if is_macos ; then
    cmd='brew install'
  elif is_debian ; then
    cmd='sudo apt-get install -y'
  else
    echo 'Unable to resolve package manager'
    exit 1
  fi
  collect_packages
  collect_os_specific_packages

  eval "$cmd"
}

function make_link () {
  ln -sfv "$1" "$2"
}

function create_link_at_home () {
  create_nest_at_home "$1" ''
}

function destroy_at_home () {
  rm -rf "${DOTFILES_USER_HOME:?}/$1"
}

function create_nest_at_home() {
  # shellcheck disable=SC2154
  make_link "${DOTFILES_FULL_PATH:?}/$1" "${DOTFILES_USER_HOME}$2"
}

function create_tool_link_at_home() {
  create_link_at_home "tools/$1"
}

function rm_link_at_home () {
  rm -f "${DOTFILES_USER:?}/$1"
}

function clone_from_github () {
    folder_name="${1##*/}"
    folder_name="${folder_name%%\.*}"
    folder_name="$DOTFILES_FULL_PATH/repos/$folder_name"
    tag="$2"

    if ! [ -d "$folder_name" ] ; then
      git clone --depth 1 "https://github.com/$1" "$folder_name"
    fi
    cd "$folder_name" || exit 1
    git fetch --tags
    if [ -n "$tag" ] ; then 
      git config --local advice.detachedHead false
      git checkout "$tag" 
    fi
}

function skip_if_tool_is_not_installed () {
  command_exists "$1" || { echo " ---> skipping: [$2] because [$1] is required for it"; exit 0; }
}

function skip_if_installed () {
  tool="${1:-$DOTFILES_CURRENT_TOOL}"
  if (( ${DOTFILES_UPDATE_RUN:-0} )) ; then
    DOTFILES_SHOULD_STOP_CURRENT=0
    return
  fi
  if ! (( "${DOTFILES_SHOULD_STOP_CURRENT:-0}" )) ; then
    if command_exists "$tool" \
      || [ -d "$DOTFILES_BIN/$tool" ] \
      || [ -f "$DOTFILES_BIN/cargo/bin/$tool" ] ; then
      export DOTFILES_TOOL_ALREADY_INSTALLED=1
      export DOTFILES_SHOULD_STOP_CURRENT=1
    fi
  fi
}

function skip_if_dir_exists () {
  dir="$1"
  if ! (( "${DOTFILES_SHOULD_STOP_CURRENT:-0}" )) ; then
    if [ -d "$dir" ]; then
      export DOTFILES_TOOL_ALREADY_INSTALLED=1
      export DOTFILES_SHOULD_STOP_CURRENT=1
    fi
  fi
}

