#!/usr/bin/env bash

function install_brew_casks() {
  brew cask install \
    google-chrome \
    firefox \
    intellij-idea-ce \
    slack
}

function epath () {
  echo $PATH | sed s/:/\\n/g | sort | uniq
}

function clone_from_github () {
  local repo="$1"
  local folder_name=~/dotfiles/repos
  local tag="$2"

  clone_from_github_into_dir "$repo" "$folder_name" "$tag"
}

function clone_from_github_into_dir () {
  set -x
  repo="$1"
  tag="$3"
  name="${repo##*/}"
  folder_name="$2"/"$name"

  if ! [ -d "$folder_name" ] ; then
    local url="https://github.com/$repo"
    git clone --depth 1 "$url" "$folder_name"
  fi
  cd "$folder_name" || exit 1
  git fetch --tags
  if [ -n "$tag" ] ; then 
    echo "Checking out $repo to $tag"
    git config --local advice.detachedHead false
    git checkout "$tag" 
  fi
  set +x
}

function install_go() {
  set -x
  local arch="$1"
  local go_version="$DFILES_VERSION_GO"
  local bin_dir="$DFILES_DIR_BIN/go"
  local user="$DFILES_USER"
  local tarball=go"$go_version"."$arch".tar.gz

  rm -rf "$bin_dir"
  wget -q "https://dl.google.com/go/${tarball}"
  mkdir -p "$bin_dir"
  tar -xf "$tarball" -C "$DFILES_DIR_BIN"
  rm -f "$tarball"
  set +x

  echo "Try go help"
}

function install_nvim() {
  set +x
  current=$(pwd)
  mkdir -p "$XDG_DATA_HOME"/nvim || echo "No permissions to create 'nvim' under $XDG_DATA_HOME"
  mkdir -p "$XDG_CONFIG_HOME"/nvim || echo "No permissions to create 'nvim' under $XDG_CONFIG_HOME"

  clone_from_github 'neovim/neovim' 'stable'
  rm -rf build/  # clear the CMake cache
  make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$DFILES_PATH_NVIM"
  sudo make install
  cd "$current" || exit 1
  set -x

  echo 'Try nvim'
}

function install_fzf() {
  curr=$(pwd)
  clone_from_github 'junegunn/fzf' "$DFILES_VERSION_FZF"
  # shellcheck disable=1090
  ./install --key-bindings --completion --no-update-rc --no-fish
  cd "$curr" || exit 1
  echo 'Try fzf --help'
}

function install_rustup() {
  set -x
  local default_host_triple="$1"
  local user="$DFILES_USER"

  if command_exists rustup ; then
    echo 'Rustup already installed'
  fi
  
  mkdir -p "$DFILES_PATH_CARGO"

  curl -sSL -o setup-rust https://sh.rustup.rs
  chmod +x setup-rust

  echo 'Running the install tool...'
  if [ -z "$default_host_triple" ]; then
    ./setup-rust -y --no-modify-path --default-toolchain stable
  else
    ./setup-rust -y --no-modify-path --default-host "$default_host_triple" --default-toolchain stable
  fi

  echo 'Cleaning up...'
  rm -rf setup-rust

  sudo chown -R "$user":"$user" "$DFILES_PATH_CARGO"

  set +x
  echo 'Try rustup --help'
}

function install_sdkman() {
  if ! [ -d "$SDKMAN_DIR" ]; then
    curl -sSL https://get.sdkman.io | bash
  fi
}

function install_nvm() {
  if [ -d "$NVM_DIR" ] ; then
    echo 'nvm already installed'
  fi
  set +x
  curr=$(pwd)
  clone_from_github 'nvm-sh/nvm' "$NVM_DIR" "$DFILES_VERSION_NVM"
  "$NVM_DIR"/install.sh
  cd "$curr" || exit 1

  # shellcheck disable=1090
  . "$NVM_DIR/nvm.sh" 

  nvm install "$DFILES_VERSION_NODEJS"
  set -x
}

function remove_write_for_groups_on_insecure_dirs() {
  compaudit | xargs chmod g-w
}

function install_zsh_plugins() {
  if command_exists 'zsh' ; then 

    local zsh_plugins_repos_dir=~/dotfiles/repos/zsh-plugins
    # at this point zsh is expected to be installed with a package manager
    mkdir -p "$zsh_plugins_repos_dir"

    clone_from_github_into_dir 'ohmyzsh/ohmyzsh' "$zsh_plugins_repos_dir"
    clone_from_github_into_dir 'wfxr/forgit' "$zsh_plugins_repos_dir"
    clone_from_github_into_dir "b4b4r07/enhancd" "$zsh_plugins_repos_dir"
    clone_from_github_into_dir "zdharma/fast-syntax-highlighting" "$zsh_plugins_repos_dir"
    clone_from_github_into_dir "zsh-users/zsh-history-substring-search" "$zsh_plugins_repos_dir"
    if ! is-rpi ; then
      clone_from_github_into_dir "zsh-users/zsh-autosuggestions" "$zsh_plugins_repos_dir"
      clone_from_github_into_dir "zsh-users/zsh-completions" "$zsh_plugins_repos_dir"
    fi
  fi
}

function make_links() {
  ln -sfv ~/dotfiles/.gitconfig ~/.gitfconfig
  ln -sfv ~/dotfiles/.ctags ~/.ctags
  ln -sfv ~/dotfiles/.zshrc ~/.zshrc
  ln -sfv ~/dotfiles/.bashrc ~/.bashrc
  ln -sfv ~/dotfiles/.vimrc ~/.vimrc
  ln -sfv ~/dotfiles/.ideavimrc ~/.ideavimrc
  ln -sfv ~/dotfiles/.minvimrc ~/.minvimrc
  ln -sfv ~/dotfiles/.vim ~/.vim
  ln -sfv ~/dotfiles/.tmux.conf ~/.tmux.conf
  ln -sfv ~/dotfiles/.Xdefaults ~/.Xdefaults
}

function install_tpm() {
  set -x
  curr=$(pwd)
  clone_from_github 'tmux-plugins/tpm' 'v3.0.0'
  cd "$curr" || exit 1
  set +x
}

function shck_one () {
    shellcheck --external-sources --external-sources --format=tty --exclude=SC1090,1091 --shell=bash "$1"
}

function shck_dotfiles_recursive () {
  dir="$1"
  while IFS= read -r -d '' f
  do
    shck_one "$f"
  done <   <(find "$dir" -type f \( -name "*.sh" -or -name '*.alias' -or -name '*.functions' -or -name '*.env' \) -print0)
}

function shck_dotfiles () {
  shck_dotfiles_recursive "$DOTFILES_FULL_PATH/tools"
  shck_one "$DOTFILES_FULL_PATH/install.sh"
  shck_one "$DOTFILES_FULL_PATH/funcs.sh"
  shck_one "$DOTFILES_FULL_PATH/funcs.min.sh"
}

# --leds_off({0 | 1}) {
function leds_off () {
  if is_rpi ; then
    echo "$1" | sudo tee /sys/class/leds/led0/brightness
    echo "$1" | sudo tee /sys/class/leds/led1/brightness
  else
    echo 'Leds only controllable in RPI'
  fi
}

function print_cmd_exists() {
  if command_exists "$1"
  then
    echo 'yes'
  else
    echo 'no'
  fi
}

function command_exists() {
  type "$1" 1>/dev/null 2>/dev/null
}

function is_rpi () {
  check_os 'rpi'
}

function is_linux () {
  check_os 'ubuntu|rpi'
}

function is_debian () {
  check_os 'ubuntu|rpi'
}

function is_ubuntu () {
  check_os 'ubuntu'
}

function is_unix () {
  check_os 'mac|ubuntu|rpi'
}

function check_os () {
  if [ -z "$DOTFILES_RESOLVED_OS" ] ; then
    find_os
  fi
  [[ "$DOTFILES_RESOLVED_OS" =~ $1 ]]
}

function find_os () {
  if [ -z "$DOTFILES_RESOLVED_OS" ] ; then
    supported_oses='mac, rpi, ubuntu'
    os=''
    if [ -f /etc/os-release ] ; then
      os_release=$(cat /etc/os-release)
    fi
    if is_macos ; then
      os='mac'
    elif [[ "$os_release" =~ 'Ubuntu' ]]; then
      os='ubuntu'
    elif [[ "$os_release" =~ 'Raspbian' ]] ; then
      os='rpi'
    else
      echo "__FAIL: unable to detect os. Should be one of: $supported_oses"
      read -r input_os
      os="$input_os"
    fi
    export DOTFILES_RESOLVED_OS="$os"
  fi
}

function is_macos () {
  [[ "$OSTYPE" =~ 'darwin' ]] || return 1
}

function configure_vim() {
  ln -sfv ~/dotfiles/init.vim "$XDG_CONFIG_HOME"/nvim/init.vim

  if ! [ -f ~/dotfiles/.vim/colors/gruvbox.vim ] ; then
    curl -fLo ~/dotfiles/.vim/colors/gruvbox.vim --create-dirs \
      https://raw.githubusercontent.com/morhetz/gruvbox/master/autoload/gruvbox.vim
  fi
  
  if ! [ -f ~/dotfiles/.vim/colors/simple-dark.vim ] ; then
    curl -fLo ~/dotfiles/.vim/colors/simple-dark.vim --create-dirs \
      https://raw.githubusercontent.com/zefei/simple-dark/master/colors/simple-dark.vim
  fi

  if ! [ -f ~/dotfiles/.vim/autoload/plug.vim ] ; then
    curl -fLo ~/dotfiles/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  fi
  if ! [ -f ~/dotfiles/.vim/autoload/plug.vim ] ; then
    curl -fLo "${XDG_DATA_HOME}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  fi
}
