theme = "everforest_dark"

[editor]
line-number = 'relative'
cursorline = true
bufferline = 'multiple'

[editor.cursor-shape]
insert = 'bar'
normal = 'block'
select = 'underline'

[editor.file-picker]
hidden = false
# shell = ["zsh"]

[editor.statusline]
left = ["mode", "spinner", "total-line-numbers", "file-modification-indicator", "file-name"]
center = ["version-control"]
right = ["diagnostics", "position", "position-percentage", "selections", "file-encoding", "file-line-ending", "file-encoding", "file-type"]
separator = "│"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.whitespace]
render = 'none'

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.normal]
C-A-q = ":theme everforest_light"
C-A-w = ":theme everforest_dark"
C-A-o = ":config-open"
C-A-r = ":config-reload"
C-A-h = ":buffer-previous"
C-A-l = ":buffer-next"
A-w = ":buffer-close"
C-s = ":w"
C-A-s = ":write-all"
C-A-x = ":quit-all"
C-q = ":quit"
G = "goto_file_end"
R = "goto_file_start"
X = "extend_line_above"
