#!/usr/bin/env bash 

. funcs

if ! command_exists 'brew' ; then 
  printf "Install brew: %s then come back\n" 'https://brew.sh/'
  return 0
fi

. configure

user=$(id -u -n)
export DFILES_USER="$user"

brew update
brew install \
  the_silver_searcher \
  exa \
  neovim \
  ctags \
  gawk \
  zip \
  shellcheck \
  tmux \
  zsh \
  wget \
  openjdk@8 \
  openjdk@11

install_brew_casks

sudo python -m ensurepip
sudo pip install --upgrade pip
sudo pip install \
  jedi \
  python-language-server \
  pathlib \
  typing \
  vim-vint

install_fzf
install_go 'darwin-amd64'
install_rustup 'x86_64-apple-darwin'

go get github.com/hairyhenderson/gomplate/cmd/gomplate
go get github.com/tomnomnom/gron

cargo install --force \
  bat \
  mdcat

npm install -g \
  eslint \
  livedown \
  dockerfile-language-server-nodejs \
  bash-language-server \
  fixjson \
  markdownlint-cli2 \
  eslint-config-prettier  \
  prettier \
  elm \
  elm-test \
  elm-oracle \
  elm-format

install_zsh_plugins
make_links
configure_neovim
