#!/usr/bin/env bash 

. funcs-export
. funcs
. configure

user=$(id -u -n)
export DFILES_USER="$user"

sudo apt-get -y update

sudo apt-get -y install \
  ninja-build \
  libtool \
  libtool-bin \
  autoconf \
  automake \
  cmake \
  g++ \
  pkg-config \
  unzip \
  build-essential \
  libssl-dev \
  gawk \
  zip \
  shellcheck \
  vim \
  zsh \
  python-pip \
  python3-pip

ln -sfv ~/dotfiles/tools/ctags/.ctags ~/.ctags

install_nvim
install_go 'linux-armv6l'
install_rustup 'armv7-unknown-linux-gnueabihf'

cargo install --force \
  exa \
  bat \
  mdcat

install_zsh_plugins
