#!/usr/bin/env bash 

function setup() {
  . funcs
  . configure

  user=$(id -u -n)
  export DFILES_USER="$user"
  echo "Sourced funcs and configure. User is $DFILES_USER"
}

function apt_update() {
  sudo apt-get -y update
}

function apt_install() {
  # gettext - needed to install nvim. Ubuntu 18.04 doesn't have it by default
  sudo apt-get -y install \
    ninja-build \
    libtool \
    libtool-bin \
    autoconf \
    automake \
    cmake \
    g++ \
    pkg-config \
    unzip \
    gnome-tweaks \
    build-essential \
    libssl-dev \
    ctags \
    gawk \
    shellcheck \
    youtube-dl \
    zsh \
    python3-pip \
    silversearcher-ag \
    apt-utils \
    jq \
    rng-tools \
    gettext
}

function pip_install() {
  pip3 install \
    jedi \
    python-language-server \
    pathlib \
    typing \
    vim-vint
}

function yubi_req_install () {
  sudo apt -y install gnupg2 \
    gnupg-agent \
    dirmngr \
    cryptsetup \
    scdaemon \
    pcscd \
    secure-delete \
    hopenpgp-tools \
    yubikey-personalization \
    python3-pip \
    python3-pyscard

  pip3 install \
    PyOpenSSL \
    yubikey-manager

  sudo service pcscd start
}

function install_go_packages() {
  set -x
  go get github.com/hairyhenderson/gomplate/cmd/gomplate
  go get github.com/tomnomnom/gron
  go get github.com/mikefarah/yq/v3
  set +x
}

function install_cargo_packages() {
  cargo install --force \
    exa \
    bat \
    mdcat
}

function install_docker() {
  sudo apt update
  sudo apt install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  sudo apt-key fingerprint 0EBFCD88
  sudo add-apt-repository \
     "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
     $(lsb_release -cs) \
     stable"

  sudo apt update
  sudo apt install -y docker-ce docker-ce-cli containerd.io
}

function configure_docker() {
  if grep -q docker /etc/group ; then
    echo 'group "docker" already exists'
  else
    echo 'creating group "docker"'
    sudo groupadd docker
  fi
  sudo usermod -aG docker "$USER"
  newgrp docker
}

function install_docker_compose() {
  location="$DFILES_DIR_BIN"/docker-compose
  sudo curl -L "https://github.com/docker/compose/releases/download/1.28.2/docker-compose-$(uname -s)-$(uname -m)" -o "$location"
  sudo chmod +x "$location"
}

function install_npm_packages() {
  npm install -g \
    eslint \
    livedown \
    dockerfile-language-server-nodejs \
    bash-language-server \
    fixjson \
    markdownlint-cli2 \
    eslint-config-prettier \
    prettier \
    elm \
    elm-test \
    elm-oracle \
    elm-format
}

function customize_regolith() {
  sudo apt install -y regolith-look-nord
  regolith-look set nord
  regolith-look refresh
}

# add ~/.local/bin to path
function run() {
  setup
  apt_update
  apt_install
  pip_install
  install_nvim
  install_fzf
  install_go_linux
  install_rustup_linux
  install_go_packages
  install_cargo_packages
  install_npm_packages
  install_zsh_plugins
  make_links
  configure_neovim
}

function install_gauge() {
  # https://docs.gauge.org/getting_started/installing-gauge.html?os=linux&language=javascript&ide=vscode
  sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 023EDB0B
  echo deb https://dl.bintray.com/gauge/gauge-deb stable main | sudo tee -a /etc/apt/sources.list
  sudo apt update && sudo apt install -y gauge
}
