#!/usr/bin/env bash 

. funcs
. configure

user=$(id -u -n)
export DFILES_USER="$user"

sudo apt-get -y update

sudo apt-get -y install \
  ninja-build \
  libtool \
  libtool-bin \
  autoconf \
  automake \
  cmake \
  g++ \
  pkg-config \
  unzip \
  gnome-tweaks \
  build-essential \
  libssl-dev \
  ctags \
  gawk \
  zip \
  shellcheck \
  tmux \
  vim \
  youtube-dl \
  zsh \
  python-pip \
  python3-pip \
  silversearcher-ag \
  apt-utils \
  npm \
  jq \
  yq

pip install \
  jedi \
  python-language-server \
  pathlib \
  typing \
  vim-vint

install_llvm
install_nvim
install_fzf
install_nvm
install_go 'linux-amd64'
install_rustup 'x86_64-unknown-linux-gnu'
install_sdkman
install_tpm

set -x
go get github.com/hairyhenderson/gomplate/cmd/gomplate
go get github.com/tomnomnom/gron
set +x

cargo install --force \
  exa \
  bat \
  mdcat

npm install -g \
  eslint \
  livedown \
  dockerfile-language-server-nodejs \
  bash-language-server \
  fixjson \
  markdownlint-cli2 \
  eslint-config-prettier \
  prettier \
  elm \
  elm-test \
  elm-oracle \
  elm-format

install_zsh_plugins

make_links
configure_vim

function install_llvm() {
  if [ -f /usr/bin/clangd ] && [ -f /usr/bin/llvm-config ] ; then
    return
  fi
  # From http://apt.llvm.org/
  wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
  # Fingerprint: 6084 F3CF 814B 57C1 CF12 EFD5 15CF 4D18 AF4F 7421

  sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main'

  sudo apt-get update
  sudo apt-get -y install \
    libllvm-8-ocaml-dev \
    libllvm8 \
    llvm-8 \
    llvm-8-dev \
    llvm-8-doc \
    llvm-8-examples \
    llvm-8-runtime \
    clang-8 \
    clang-tools-8 \
    clang-8-doc \
    libclang-common-8-dev \
    libclang-8-dev \
    libclang1-8 \
    clang-format-8 \
    python-clang-8 \
    libclang1 \
    libclang-dev

  sudo update-alternatives --install /usr/bin/clangd clangd /usr/bin/clangd-8 100
  sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-8 100
}

