#!/usr/bin/env bash 

function setup() {
  . funcs
  . configure

  user=$(id -u -n)
  export DFILES_USER="$user"
  echo "Sourced funcs and configure. User is $DFILES_USER"
}

function apt_update() {
  sudo apt-get -y update
}

function apt_install() {
  # gettext - needed to install nvim. Ubuntu 18.04 doesn't have it by default
  sudo apt-get -y install \
    ninja-build \
    libtool \
    libtool-bin \
    autoconf \
    automake \
    cmake \
    g++ \
    pkg-config \
    unzip \
    gnome-tweaks \
    build-essential \
    libssl-dev \
    ctags \
    gawk \
    shellcheck \
    youtube-dl \
    zsh \
    python3-pip \
    silversearcher-ag \
    apt-utils \
    jq \
    rng-tools \
    gettext
}

function pip_install() {
  pip3 install \
    jedi \
    python-language-server \
    pathlib \
    typing \
    vim-vint
}

function install_go_packages() {
  set -x
  go get github.com/hairyhenderson/gomplate/cmd/gomplate
  go get github.com/tomnomnom/gron
  go get github.com/mikefarah/yq/v3
  set +x
}

function install_cargo_packages() {
  cargo install --force \
    exa \
    bat \
    mdcat
}

function install_npm_packages() {
  npm install -g \
    eslint \
    livedown \
    dockerfile-language-server-nodejs \
    bash-language-server \
    fixjson \
    markdownlint-cli2 \
    eslint-config-prettier \
    prettier \
    elm \
    elm-test \
    elm-oracle \
    elm-format
}

function customize_regolith() {
  sudo apt install -y regolith-look-nord
  regolith-look set nord
  regolith-look refresh
}

# add ~/.local/bin to path

function run() {
  setup
  apt_update
  apt_install
  pip_install
  install_nvim
  install_fzf
  install_go 'linux-amd64'
  install_rustup 'x86_64-unknown-linux-gnu'
  install_go_packages
  install_cargo_packages
  install_npm_packages
  install_zsh_plugins
  make_links
  configure_neovim
}

