#!/usr/bin/env bash

echo "Will do:"
echo "  - username: $DOTFILES_USER"
echo "  - install go $DOTFILES_GO_VERSION in $DOTFILES_GOLANG_ROOT"
echo "  - go path set to $DOTFILES_GOLANG_GOPATH"

if is_rpi ; then
  arch='linux-armv6l'
elif is_ubuntu ; then
  arch='linux-amd64'
elif is_macos ; then
  arch='darwin-amd64'
else
  echo 'No arch defined. Aborting golang'
  exit 1
fi
tarball=go"$DOTFILES_GO_VERSION"."$arch".tar.gz
echo "Downloading go$DOTFILES_GO_VERSION.${arch}.tar.gz..."

rm -rf "$DOTFILES_BIN/go"
wget -q "https://dl.google.com/go/${tarball}"
tar -xf "$tarball" -C "$DOTFILES_BIN"
rm -f "$tarball"

echo "Changing ownership of $DOTFILES_GOLANG_ROOT to $DOTFILES_USER"
sudo chown -R "$DOTFILES_USER:$DOTFILES_USER" "$DOTFILES_GOLANG_ROOT"

echo "go $DOTFILES_GO_VERSION is installed. Try go help"
