#!/usr/bin/env bash

curr=$(pwd)
git clone --depth 1 https://github.com/junegunn/fzf.git "$DOTFILES_FZF_DIR"
echo "Installing fzf@$DOTFILES_FZF_VERSION"
cd "$DOTFILES_FZF_DIR" || exit 1
# shellcheck disable=1090
./install --key-bindings --completion --no-update-rc --no-fish
cd "$curr" || exit 1

