#!/usr/bin/env bash

curl -fLo "$DOTFILES_FULL_PATH"/tools/vim/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

repo_folder="$DOTFILES_FULL_PATH/repos/vim-plug"
clone_from_github 'junegunn/vim-plug' "$repo_folder" '0.10.0'

autoload_folder="$DOTFILES_FULL_PATH/tools/vim/.vim/autoload"
mkdir -p "$autoload_folder"

cp "$repo_folder/plug.vim" "$autoload_folder/plug.vim"

