#!/usr/bin/env bash

curr=$(pwd)
clone_from_github 'junegunn/vim-plug' '0.10.0'

autoload_folder="$DOTFILES_FULL_PATH/tools/vim/.vim/autoload"
mkdir -p "$autoload_folder"

cd "$curr" || exit 1
cp "$DOTFILES_FULL_PATH/repos/vim-plug/plug.vim" "$autoload_folder/plug.vim"

