#!/usr/bin/env bash

if is_ubuntu ; then
  echo 'Installing prerequisites to build neovim...'

  export CMAKE_INSTALL_PREFIX="$DOTFILES_NVIM_INSTALLATION"

  install_with_pkg_manager 'ninja-build libtool libtool-bin autoconf automake cmake g++ pkg-config unzip'

  current=$(pwd)
  clone_from_github 'neovim/neovim' 'stable'
  rm -rf build/  # clear the CMake cache
  make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$DOTFILES_NVIM_INSTALLATION"
  make install
  cd "$current" || exit 1
fi
