#!/usr/bin/env bash 

if command_exists 'zsh' ; then 

  # at this point zsh is expected to be installed with a package manager
  mkdir -p "$DFILES/repos/zsh-plugins"

  clone_from_github 'ohmyzsh/ohmyzsh'

  #zplug "plugins/globalias", from:oh-my-zsh
  #zplug "plugins/vi-mode", from:oh-my-zsh
  #zplug "plugins/dotenv", from:oh-my-zsh
  clone_from_github 'wfxr/forgit'

  zplug "b4b4r07/enhancd", use:"init#.sh"
  #zplug "Cloudstek/zsh-plugin-appup"
  #zplug "hlissner/zsh-autopair"
  #zplug "zdharma/fast-syntax-highlighting"
  #zplug "wfxr/forgit"
  #zplug "stedolan/jq", from:gh-r, as:command, rename-to:jq
  #zplug "mikefarah/yq", from:gh-r, as:command, rename-to:yq, lazy:true
  #zplug "lunaryorn/mdcat", from:gh-r, as:command, rename-to:mdcat, if:"! is-rpi"
  #zplug "raylee/tldr", as:command, use:"tldr"
  #zplug "Cloudstek/zsh-plugin-appup"
  #zplug "zdharma/fast-syntax-highlighting"
  #zplug "b4b4r07/easy-oneliner", on:"junegunn/fzf-bin"
  #zplug "zsh-users/zsh-history-substring-search"
  #zplug "sindresorhus/pure"
  #zplug "zsh-users/zsh-autosuggestions", if:"! is-rpi"
  #zplug "zsh-users/zsh-completions", if:"! is-rpi"
  #zplug "greymd/tmux-xpanes"

fi
