bind r source-file ~/.tmux.conf \; display "Reloaded .tmux.conf"

setw -g mode-keys vi
set -g default-terminal "screen-256color"

# set pane colors - highlight the active pane
#set-option -g pane-border-fg colour235 #base02
#set-option -g pane-active-border-fg colour240 #base01

# set color for status bar
set-option -g renumber-windows on

# do not rename windows automatically
set-option -g allow-rename off

# pane resizing
bind k resize-pane -U 5
bind j resize-pane -D 5
bind h resize-pane -L 5
bind l resize-pane -R 5

# No prompts
bind-key & kill-window
bind-key x kill-pane

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-x
bind-key C-x send-prefix

# intutive pane splitting
bind | split-window -h -c "#{pane_current_path}"
bind \ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
unbind %
unbind '"'

# vi mode copy
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle

set -g @sidebar-tree-command 'tree -C'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-sidebar'
run '~/.tmux/plugins/tpm/tpm'
