#!/usr/bin/env bash

default_host_triple=''
if is_rpi ; then
  # assume raspberry pi
  default_host_triple='armv7-unknown-linux-gnueabihf'
elif is_ubuntu ; then
  install_with_pkg_manager 'build-essential libssl-dev pkg-config'
  default_host_triple='x86_64-unknown-linux-gnu'
elif is_macos ; then
  default_host_triple='x86_64-apple-darwin'
else
  echo 'Unable to set default-host-triple automatically'
fi


echo 'Downloading rust...'
curl -sSL -o setup-rust https://sh.rustup.rs

echo 'Making it executable...'
chmod +x setup-rust

echo 'Running the install tool...'
if [ -z "$default_host_triple" ]; then
  ./setup-rust -y --no-modify-path --default-toolchain stable
else
  ./setup-rust -y --no-modify-path --default-host "$default_host_triple" --default-toolchain stable
fi

echo 'Cleaning up...'
rm -rf setup-rust

sudo chown -R "$DOTFILES_USER":"$DOTFILES_USER" "$DOTFILES_CARGO_PATH"

echo 'Rust installation process complete. Try rustup --help to ensure is installed!'
